services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/config/traefik/dynamic.yml"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - mediacenter
    ports:
      - "32760:80"
      - "32761:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../config/traefik/dynamic.yml:/config/traefik/dynamic.yml:ro
      - ../secrets/certs:/certs:ro
